
get 'issue_templates/preview', :to => 'issue_templates#preview'
get 'projects/:project_id/issue_templates_settings/:action', :to => 'issue_templates_settings'
get 'global_issue_templates/preview', :to => 'global_issue_templates#preview'

get 'projects/:project_id/issue_templates/:action', :to => 'issue_templates'
get 'projects/:project_id/issue_templates/:action/:id', :to => 'issue_templates#edit'
get 'projects/:project_id/issue_templates/move/:id', :to => 'issue_templates#move_to'
get 'projects/:project_id/issue_templates_settings/:action', :to => 'issue_templates_settings'
get 'issue_templates/preview', :to => 'issue_templates#preview'
get 'projects/:project_id/issue_templates_settings/preview', :to => 'issue_templates_settings#preview'
get 'global_issue_templates/:action', :to => 'global_issue_templates'
get 'global_issue_templates/:action/:id', :to => 'global_issue_templates#edit'
patch 'global_issue_templates/:action/:id', :to => 'global_issue_templates#edit'
get 'global_issue_templates/preview', :to => 'global_issue_templates#preview'

post 'projects/:project_id/issue_templates/:action', :to => 'issue_templates'
post 'projects/:project_id/issue_templates/:action/:id', :to => 'issue_templates#edit'
post 'projects/:project_id/issue_templates_settings/:action', :to => 'issue_templates_settings'
post 'issue_templates/preview', :to => 'issue_templates#preview'
post 'projects/:project_id/issue_templates_settings/preview', :to => 'issue_templates_settings#preview'
post 'global_issue_templates/:action', :to => 'global_issue_templates'
post 'global_issue_templates/:action/:id', :to => 'global_issue_templates#edit'
post 'global_issue_templates/preview', :to => 'global_issue_templates#preview'
